// define([
//   "梓胥",
//   "李磊", "俊义", "兰玉",
//   "泥巴", "对剑", "希普", "牧木", "夏雩", "衡芜", "钝刀", "苍新", "琳心", "玉鼎", "冯衡", "伍举", "长松", "卫海", "伯川", "道潜", "丁勉", "竹棒", "妙才", "许由", "祢衡", "赵盾", "斗子文", "寇恂", "极天", "秦天", "裴秀", "花朝", "静俭", "墨颜", "王维", "马武", "公孙龙", "甘德", "流珠", "路悠", "樽空", "沐峰", "清筠", "绝伦", "星辰", "羽单", "伯兮", "郝思文", "聂壹", "南岸", "明恽", "君乾",
//   "飞天", "文赢", "义均", "文和", "曹彬", "晁错", "兔葵", "苏星河", "太常", "北湖", "弘殷", "吕蒙", "颜良", "庄辛", "崇幻", "贝儿", "柏平", "小毛", "战尘", "子盛", "问柏", "湛然", "独慕", "浴尘", "公与", "桑美", "晏婴", "严成方", "连挚", "汪信之", "楚天", "良臣", "暮城", "塔石", "薇达", "行洋", "明何", "昔空", "蓝玉", "韩当", "丛英", "吞佛", "真岚", "仲文", "吕方", "郑天寿", "一恒", "誉少", "无竞", "九弦",
//   "玉伯", "冒顿", "啸生", "尹曰", "臻儿", "籽沐", "余化", "玉郎", "右丞", "默哈", "血诺", "桐杰", "镜曦", "沉鱼", "贯高", "陆辉", "浩初", "天材", "偏右", "云谦", "乔花", "展新", "张初尘", "宫煌",
//   "宗玄", "一正", "若夷", "普渡", "晴汐", "徒离",
//   "仲景", "大禹", "徐盛", "木合", "郭淮", "方嘉", "李渔", "长皓", "渔樵", "惜年", "沧溟", "东隅", "海涛", "磻溪"
// ]);

define([
    ['p-1', './src/img/people/p-1.png'],
    ['p-2', './src/img/people/p-2.png'],
    ['p-3', './src/img/people/p-3.png'],
    ['p-4', './src/img/people/p-4.png'],
    ['p-5', './src/img/people/p-5.png'],
    ['p-6', './src/img/people/p-6.png'],
    ['p-7', './src/img/people/p-7.png'],
    ['p-8', './src/img/people/p-8.png'],
    ['p-9', './src/img/people/p-9.png'],
    ['p-10', './src/img/people/p-10.png'],
    ['p-11', './src/img/people/p-11.png'],
    ['p-12', './src/img/people/p-12.png'],
    ['p-13', './src/img/people/p-13.png'],
    ['p-14', './src/img/people/p-14.png'],
    ['p-15', './src/img/people/p-15.png'],
    ['p-16', './src/img/people/p-16.png'],
    ['p-17', './src/img/people/p-17.png'],
    ['p-18', './src/img/people/p-18.png'],
    ['p-19', './src/img/people/p-19.png'],
    ['p-20', './src/img/people/p-20.png'],
    ['p-21', './src/img/people/p-21.png'],
    ['p-22', './src/img/people/p-22.png'],
    ['p-23', './src/img/people/p-23.png'],
    ['p-24', './src/img/people/p-24.png'],
    ['p-25', './src/img/people/p-25.png'],
    ['p-26', './src/img/people/p-26.png'],
    ['p-27', './src/img/people/p-27.png'],
    ['p-28', './src/img/people/p-28.png'],
    ['p-29', './src/img/people/p-29.png'],
    ['p-30', './src/img/people/p-30.png'],
    ['p-31', './src/img/people/p-31.png'],
    ['p-32', './src/img/people/p-32.png'],
    ['p-33', './src/img/people/p-33.png'],
    ['p-34', './src/img/people/p-34.png'],
    ['p-35', './src/img/people/p-35.png'],
    ['p-36', './src/img/people/p-36.png'],
    ['p-37', './src/img/people/p-37.png'],
    ['p-38', './src/img/people/p-38.png'],
    ['p-39', './src/img/people/p-39.png'],
    ['p-40', './src/img/people/p-40.png'],
    ['p-41', './src/img/people/p-41.png'],
    ['p-42', './src/img/people/p-42.png'],
    ['p-43', './src/img/people/p-43.png'],
    ['p-44', './src/img/people/p-44.png'],
    ['p-45', './src/img/people/p-45.png'],
    ['p-46', './src/img/people/p-46.png'],
    ['p-47', './src/img/people/p-47.png'],
    ['p-48', './src/img/people/p-48.png'],
    ['p-49', './src/img/people/p-49.png'],
    ['p-50', './src/img/people/p-50.png'],
    ['p-51', './src/img/people/p-51.png'],
    ['p-52', './src/img/people/p-52.png'],
    ['p-53', './src/img/people/p-53.png'],
    ['p-54', './src/img/people/p-54.png'],
    ['p-55', './src/img/people/p-55.png'],
    ['p-56', './src/img/people/p-56.png'],
    ['p-57', './src/img/people/p-57.png'],
    ['p-58', './src/img/people/p-58.png']
]);